# Generated by Django 2.1.15 on 2023-09-23 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('id_heroe', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField(null=True)),
                ('origen', models.CharField(max_length=100)),
                ('habilidades', models.TextField(blank=True)),
                ('poderes', models.TextField(blank=True)),
            ],
        ),
    ]
