# Generated by Django 2.1.15 on 2023-09-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroe',
            name='id_heroe',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
