# Generated by Django 2.1.15 on 2023-09-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reto', '0002_auto_20230924_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villano',
            fields=[
                ('id_villano', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField(null=True)),
                ('origen', models.CharField(max_length=100)),
                ('habilidades', models.TextField(blank=True)),
                ('poderes', models.TextField(blank=True)),
            ],
        ),
    ]
