# Generated by Django 2.1.15 on 2023-11-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reto', '0004_pelea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroe',
            name='id_heroe',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pelea',
            name='id_pelea',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='villano',
            name='id_villano',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
