# Generated by Django 2.1.15 on 2023-11-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reto', '0006_patrocinador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrocinador',
            name='id_heroe',
        ),
        migrations.DeleteModel(
            name='Patrocinador',
        ),
    ]
