# Generated by Django 4.2.7 on 2023-11-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reto", "0008_patrocinador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroe",
            name="id_heroe",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
