# Generated by Django 4.2.7 on 2023-11-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reto", "0009_alter_heroe_id_heroe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="heroe", old_name="poderes", new_name="debilidad",
        ),
        migrations.RenameField(
            model_name="villano", old_name="poderes", new_name="debilidad",
        ),
    ]
