# Generated by Django 4.2.7 on 2023-11-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reto", "0010_rename_poderes_heroe_debilidad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patrocinador",
            name="id_patrocinador",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="pelea",
            name="id_pelea",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="villano",
            name="id_villano",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
