# Generated by Django 4.2.7 on 2023-11-13 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reto", "0011_alter_patrocinador_id_patrocinador_and_more"),
    ]

    operations = []
