# Generated by Django 4.2.7 on 2023-11-13 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reto", "0014_villano_delete_pelea"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pelea",
            fields=[
                ("id_pelea", models.AutoField(primary_key=True, serialize=False)),
                ("resultado", models.CharField(max_length=100)),
                (
                    "id_heroe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reto.heroe"
                    ),
                ),
                (
                    "id_villano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reto.villano"
                    ),
                ),
            ],
        ),
    ]
